name: Build, Lint, Test

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Handled by CircleCI
        run: |
          echo "Build, lint and test are handled by CircleCI"
